### ISSUE TITLE
Does not work with SSR

### ISSUE THREAD

**Issue by tannerkrewson** [icd2k3/react-scroll-into-view-if-needed#19]
Using next.js, I was receiving `ReferenceError: Element is not defined` presumably due to this line:

https://github.com/icd2k3/react-scroll-into-view-if-needed/blob/a4e729e35bd4c9de39a0beff015fc2fe8021f3cc/src/index.js#L39

**Comment by tony** [comment]
@icd2k3 

I also get errors on gatsby:

```
ReferenceError: Element is not defined
    at Module.../node_modules/react-scroll-into-view-if-needed/dist/es/index.js (/home/t/work/parataxic.org/www/public/webpack:/www/node_modules/react-scroll-into-view-if-needed/dist/es/index.js:450:25)
    at __webpack_require__ (/home/t/work/parataxic.org/www/public/webpack:/www/webpack/bootstrap:19:1)
    at Module../src/components/Search/reactivesearch/SearchModal.tsx (/home/t/work/parataxic.org/www/public/render-page.js:82174:90)
    at __webpack_require__ (/home/t/work/parataxic.org/www/public/webpack:/www/webpack/bootstrap:19:1)
    at Module../src/components/Search/reactivesearch/SearchBar.tsx (/home/t/work/parataxic.org/www/public/render-page.js:82065:70)
    at __webpack_require__ (/home/t/work/parataxic.org/www/public/webpack:/www/webpack/bootstrap:19:1)
    at Module../src/components/Layout/TopBar.tsx (/home/t/work/parataxic.org/www/public/render-page.js:81386:90)
    at __webpack_require__ (/home/t/work/parataxic.org/www/public/webpack:/www/webpack/bootstrap:19:1)
    at Module../src/layouts/index.tsx (/home/t/work/parataxic.org/www/public/render-page.js:82733:83)
    at __webpack_require__ (/home/t/work/parataxic.org/www/public/webpack:/www/webpack/bootswarn The path "/" errored during SSR.
Edit its component node_modules/react-scroll-into-view-if-needed/dist/es/index.js:450:25 to
resolve the error.
```

**Comment by tony** [comment]
@tannerkrewson did you find an alternative?  

not sure if this works for my case yet, if so, i may PR / fork depending on level of changes involved.

**Comment by tony** [comment]
Maybe https://github.com/gatsbyjs/gatsby/issues/25110#issuecomment-646653389

`PropTypes.instanceOf(Element)` -> `PropTypes.element`
